name: skilldev_mobapp
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'  # Updated SDK constraint

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6  # Updated to latest stable
  regexpattern: ^2.6.0
  image_picker: ^1.0.5  # Updated to latest stable
  permission_handler: ^11.0.1  # Updated to latest stable
  image_picker_for_web: ^3.0.1  # Updated to latest stable
  http: ^1.1.0  # Updated to latest stable
  flutter_plugin_android_lifecycle: ^2.0.17  # Updated to latest stable
  shared_preferences: ^2.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1  # Updated to latest stable

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/signupbackground.png
    - assets/images/login_background2.png
    - assets/images/loginbackground_nologo.png
    - assets/images/logo-removebg-preview.png
    - assets/images/username-icon.png
    - assets/images/password-129.png